# Generated by Django 5.2.12 on 2026-04-08 13:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0005_alter_joinrequest_options_and_more"),
        (
            "posts",
            "0002_rename_post_targets_platform_status_idx_pt_platform_status_idx",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="PublishJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "task_name",
                    models.CharField(
                        help_text="Dotted Celery task path, e.g. publisher.tasks.publish_target",
                        max_length=255,
                    ),
                ),
                (
                    "celery_task_id",
                    models.CharField(
                        blank=True,
                        help_text="UUID assigned by Celery at dispatch time.",
                        max_length=191,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "attempt_number",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Which attempt this job represents (1-indexed).",
                    ),
                ),
                (
                    "max_attempts",
                    models.PositiveSmallIntegerField(
                        default=3,
                        help_text="Stop retrying after this many total attempts.",
                    ),
                ),
                (
                    "retry_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When to re-enqueue after a failure. Null = no retry scheduled.",
                        null=True,
                    ),
                ),
                (
                    "result",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Success payload, e.g. {"remote_post_id": "xyz123"}',
                    ),
                ),
                (
                    "error",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text=(
                            'Structured failure info: '
                            '{"code": "...", "message": "...", "traceback": "...", "at": "..."}'
                        ),
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "org",
                    models.ForeignKey(
                        help_text="Organization this job belongs to (for RLS).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="publish_jobs",
                        to="organizations.organization",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        help_text="The specific platform/account delivery this job serves.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="publish_jobs",
                        to="posts.posttarget",
                    ),
                ),
            ],
            options={
                "db_table": "publish_jobs",
                "indexes": [
                    models.Index(
                        fields=["org", "status"], name="publish_jobs_org_status_idx"
                    ),
                    models.Index(
                        fields=["org", "target", "status"],
                        name="publish_jobs_org_target_idx",
                    ),
                    models.Index(
                        fields=["target", "status"],
                        name="publish_jobs_target_status_idx",
                    ),
                    models.Index(
                        fields=["status", "retry_at"],
                        name="publish_jobs_status_retry_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="publish_jobs_created_at_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status__in", ["pending", "running"])),
                        fields=("target",),
                        name="one_active_job_per_target",
                    )
                ],
            },
        ),
    ]
