# Generated by Django 5.2.12 on 2026-04-10 10:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('org_id', models.CharField(blank=True, db_index=True, max_length=36)),
                ('method', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=2048)),
                ('status_code', models.PositiveSmallIntegerField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='audit_logs',
                    to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(
                    fields=['org_id', 'created_at'],
                    name='audit_org_created_idx'),
                    models.Index(
                        fields=['user', 'created_at'],
                        name='audit_user_created_idx'),
                    models.Index(
                        fields=['status_code', 'created_at'],
                        name='audit_status_created_idx')],
            },
        ),
    ]
