# Generated by Django 5.2.12 on 2026-04-07 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='posttarget',
            new_name='pt_platform_status_idx',
            old_name='post_targets_platform_status_idx',
        ),
    ]
