# Generated by Django 5.2.12 on 2026-04-07 12:57

import django_tenants.postgresql_backend.base
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('organizations', '0004_joinrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='joinrequest',
            options={},
        ),
        migrations.AlterModelOptions(
            name='organizationmember',
            options={},
        ),
        migrations.RenameIndex(
            model_name='joinrequest',
            new_name='organizatio_organiz_65b27e_idx',
            old_name='organizatio_organiz_a1b2c3_idx',
        ),
        migrations.RenameIndex(
            model_name='joinrequest',
            new_name='organizatio_user_id_f7cb25_idx',
            old_name='organizatio_user_id_d4e5f6_idx',
        ),
        migrations.RenameIndex(
            model_name='joinrequest',
            new_name='organizatio_status_e802c3_idx',
            old_name='organizatio_status_g7h8i9_idx',
        ),
        migrations.RenameIndex(
            model_name='organization',
            new_name='organizatio_slug_5b8b37_idx',
            old_name='organizations_slug_idx',
        ),
        migrations.RenameIndex(
            model_name='organization',
            new_name='organizatio_billing_ce1bae_idx',
            old_name='organizations_billing_idx',
        ),
        migrations.RenameIndex(
            model_name='organization',
            new_name='organizatio_is_acti_39cf63_idx',
            old_name='organizations_active_plan_idx',
        ),
        migrations.RenameIndex(
            model_name='organizationinvitation',
            new_name='organizatio_token_779f11_idx',
            old_name='org_inv_token_idx',
        ),
        migrations.RenameIndex(
            model_name='organizationinvitation',
            new_name='organizatio_organiz_128590_idx',
            old_name='org_inv_org_email_idx',
        ),
        migrations.RenameIndex(
            model_name='organizationinvitation',
            new_name='organizatio_organiz_81c88c_idx',
            old_name='org_inv_org_used_idx',
        ),
        migrations.RenameIndex(
            model_name='organizationmember',
            new_name='organizatio_organiz_f18a08_idx',
            old_name='org_members_org_role_idx',
        ),
        migrations.RenameIndex(
            model_name='organizationmember',
            new_name='organizatio_user_id_fac103_idx',
            old_name='org_members_user_active_idx',
        ),
        migrations.AlterField(
            model_name='organization',
            name='schema_name',
            field=models.CharField(db_index=True, max_length=63, unique=True,
                                   validators=[django_tenants.postgresql_backend.base._check_schema_name]),
        ),
        migrations.AlterField(
            model_name='organization',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
