# Generated by Django 5.2.12 on 2026-04-10 10:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('organizations', '0005_alter_joinrequest_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationinvitation',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'),
                                            ('admin', 'Admin'),
                                            ('editor', 'Editor'),
                                            ('viewer', 'Viewer')],
                                   default='viewer',
                                   max_length=20),
        ),
        migrations.AlterField(
            model_name='organizationmember',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'),
                                            ('admin', 'Admin'),
                                            ('editor', 'Editor'),
                                            ('viewer', 'Viewer')],
                                   default='viewer',
                                   max_length=20),
        ),
    ]
