name: Tests

on:
  workflow_run:
    workflows: ["Migration Conflict Check"]
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest
    name: Tests
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: socialos
          POSTGRES_USER: social_user
          POSTGRES_PASSWORD: social_pwd
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U social_usser -d socialos"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

      redis:
        image: redis:7
        ports:
          - 6379:6379
        options: >-
          --health-cmd="redis-cli ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      DJANGO_SETTINGS_MODULE: socialos.settings.development
      DATABASE_URL: postgres://socialos_user:socialos_pwd@localhost:5432/socialos
      REDIS_URL: redis://localhost:6379/0
      PYTHONUNBUFFERED: 1

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.workflow_run.head_repository.full_name }}
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Run migrations
        run: |
          python manage.py migrate --noinput

      - name: Run tests
        run: |
          pytest